services:
    benchmark:
        build:
            context: .
            dockerfile: cmd/benchmark/Dockerfile
        environment:
            # minio
            MINIO_SERVER: ${MINIO_SERVER}
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
            MINIO_SECURE: ${MINIO_SECURE}
            MINIO_BUCKET: ${MINIO_BUCKET}
            MINIO_ORIGINAL_PATH: ${MINIO_ORIGINAL_PATH}
            MINIO_COMPRESSED_PATH: ${MINIO_COMPRESSED_PATH}
            MINIO_DECOMPRESSED_PATH: ${MINIO_DECOMPRESSED_PATH}
            # postgres
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
            # benchmark
            RUNS: ${RUNS}

    minio:
        image: minio/minio:RELEASE.2025-02-07T23-21-09Z
        ports:
            - "9001:9001" # TODO: REMOVE IF NOT NEEDED - WebUI
        environment:
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
        volumes:
            - minio-data:/data
        command: server /data --console-address ":9001" # TODO: REMOVE IF NOT NEEDED - WebUI - ONLY THE --console-address ":9001"

    minio-init:
        image: minio/mc:RELEASE.2025-02-08T19-14-21Z
        environment:
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
            - MINIO_SERVER=${MINIO_SERVER}
        volumes:
            - ./persistence/minio:/minio
        entrypoint: ["/bin/sh", "/minio/init.sh"]
        depends_on:
            - minio

    postgres:
        image: postgres:17.3
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports: # TODO: REMOVE IF NOT NEEDED - ONLY FOR VISUALIZATION
            - "5432:5432" # ONLY FOR VISUALIZATION
        volumes:
            - ./persistence/postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
            - postgres-data:/var/lib/postgresql/data

    rscript:
        build:
            context: .
            dockerfile: visual/Dockerfile
        volumes:
            - ./visual/scripts:/visual/scripts
            - ./visual/out:/visual/out

    # TODO: REMOVE IF NOT NEEDED - ONLY FOR DATABASE DEBUGGING
    adminer:
        image: adminer:4.8.1
        ports:
            - "8080:8080"
    # END OF TODO

volumes:
    minio-data:
    postgres-data:
