services:
    benchmark:
        build:
            context: .
            dockerfile: cmd/benchmark/Dockerfile
        environment:
            # Minio
            MINIO_SERVER: ${MINIO_SERVER}
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
            MINIO_SECURE: ${MINIO_SECURE}
            MINIO_BUCKET: ${MINIO_BUCKET}
            MINIO_ORIGINAL_PATH: ${MINIO_ORIGINAL_PATH}
            MINIO_COMPRESSED_PATH: ${MINIO_COMPRESSED_PATH}
            MINIO_DECOMPRESSED_PATH: ${MINIO_DECOMPRESSED_PATH}
            # Benchmark
            RUNS: ${RUNS}

    minio:
        image: minio/minio:RELEASE.2025-02-07T23-21-09Z
        ports:
            - "9001:9001" # TODO: REMOVE IF NOT NEEDED - WebUI
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=password
        volumes:
            - minio-data:/data
        command: server /data --console-address ":9001" # TODO: REMOVE IF NOT NEEDED - WebUI - ONLY THE --console-address ":9001"

    minio-init:
        image: minio/mc:RELEASE.2025-02-08T19-14-21Z
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=password
            - MINIO_SERVER=minio:9000
        volumes:
            - ./persistence/minio:/minio
        entrypoint: ["/bin/sh", "/minio/init.sh"]

    # TODO: add postgresql

volumes:
    minio-data:
