services:
    benchmark:
        build:
            context: .
            dockerfile: cmd/benchmark/Dockerfile

    minio:
        image: minio/minio:latest
        ports:
            - "9001:9001" # TODO: REMOVE IF NOT NEEDED - WebUI
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=password
        volumes:
            - minio-data:/data
        command: server /data --console-address ":9001" # TODO: REMOVE IF NOT NEEDED - WebUI - ONLY THE --console-address ":9001"

    minio-init:
        image: minio/mc:latest
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=password
            - MINIO_SERVER=minio:9000
        volumes:
            - ./persistence/minio:/minio
        entrypoint: ["/bin/sh", "/minio/init.sh"]

volumes:
    minio-data:
